name: delpoy to test server

on:
  push:
    branches:
      - master

jobs:
  download:
    runs-on: ubuntu-latest

    steps:

      - name: download
        run: |
          mkdir dist && cd dist && ${{ secrets.CURL_COMMAND }}

      - name: deploy
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          path: ./dist/
          remote_path: /download/
          remote_host: ${{ secrets.DEPLOY_TEST_HOST }}
          remote_user: root
          remote_port: ${{ secrets.DEPLOY_TEST_PORT }}
          remote_key: ${{ secrets.DEPLOY_TEST_KEY }}
